### ISSUE TITLE
Version broken

### ISSUE THREAD

**Issue by peshmerge** [EvanHerman/Timeline-Express#12]
Hi Evan, 

I have tried to install version(Timeline Express - v1.2) on my wordpress site, but it seems that version is not complete yet. 
For example: 
The icons are missing 
![1](https://cloud.githubusercontent.com/assets/531558/14942305/d9bd6c1a-0fb8-11e6-81cd-cae54e48906c.jpg)

![2](https://cloud.githubusercontent.com/assets/531558/14942321/6ed54d90-0fb9-11e6-94bf-1b7fbff70276.jpg)
When adding a new image for the announcement "Announcement Image", the button doesn't work.
I have tried to install it on my local machine and also on my remote server, but I got the same result.

Thanks for this awesome plugin,

Peshmerge

**Comment by EvanHerman** [comment]
Hi Peshmerge,

Did you download the zip from the repo? I will re-test this afternoon and see if I am running into the issue as well. I have been developing things on a local host install and haven't encountered the issue of the files not loading properly. 

Are those files getting 404s in their appropriate folders? 


Thanks,
Evan

**Comment by peshmerge** [comment]
Hi Evan, 

I have downloaded it from the repo! All those files got 404 error! The script couldn't find them. 
I wanted to test the version because of the feature that you can have your own template for the announcements container.

Thanks,
Peshmerge

**Comment by peshmerge** [comment]
Hi Evan, 

I have another question, but I don't know if posting it here will be wise. Thanks anyway if you give me an answer. 
It's not a problem, but it's something very important, I guess. 
Look when I navigate to http://www.wp-timelineexpress.com/examples/basic-timeline/ 
I see the beautiful time-line. Then when I click on a single announcement I will be redirected to the page of the announcement, for example :
http://www.wp-timelineexpress.com/announcement/business-meeting/
Now, if I navigate to this URL http://www.wp-timelineexpress.com/announcement/ , I mean www.domain.com/{aanouncement_slug} then I get a page with all announcements but not in a time-line format (the beautiful one). 
How can I force it that when the user asks for www.mydomain.com/{aanouncement_slug} , he gets the awesome time-line? :

Thanks,
Peshmerge Morad

**Comment by EvanHerman** [comment]
Hi Peshmerge,

When you downloaded the .zip did you change the directory contained in the .zip name from **timeline-express-Refactor-v1.2** to **timeline-express**? The paths are setup to look for a **timeline-express** directory, but when downloaded and installed from GitHub, it has a -branch_name appended to the file name. In this case it would be -Refactor-v1.2.

To answer your second question, the Timeline should initialize on the page wherever you are using the Shortcode, on page load. Do you have a link to your page as an example of where it is not working?


Thanks,
Evan

**Comment by peshmerge** [comment]
Hi Evan,

OMG! What stupid! I didn't know how did I forget to change the name of the plugin dir. You are right. I have now changed the name, and it's works perfectly. Sorry :(

For my second question: look these two pages, 
Here is the amazing time-line :
http://www.wp-timelineexpress.com/examples/basic-timeline/

Here just like a archive page of category page for announcements :
http://www.wp-timelineexpress.com/announcement/

How can I force the second page to have the same body as the first page, while you don't have acces to the second page because it's generated by the time-line-express plugin!! 
I hope you understand what I mean. 

Thanks, 
Peshmerge

**Comment by EvanHerman** [comment]
Hi Peshmerge,

At the moment the archive page does not contain the proper markup or the javascript required to initialize the timeline. 

Theoretically you should have no problems setting up a custom `archive-te_announcements.php` page template, and using a lot of the same functionality that's built into the helper files.

I can take a look and see how difficult it would be, and possible add an option - or a tutorial on how it can be achieved. It's a bit complicated for someone who's not fully comfortable with the WordPress templating system as well as the code base of Timeline Express.

Thanks!
Evan

**Comment by peshmerge** [comment]
Amazing! Thank you Evan :100:

**Comment by peshmerge** [comment]
Hi Evan, 

That was really valuable, because I have added this file archive-te_announcements.php  into my dir theme 
the content is 
<?php 
header('Location: '."http://mysite/activiteiten/");

For now is this a good solution, till I find a better solution. 

Thanks, 
Peshmerge

**Comment by EvanHerman** [comment]
No problem at all! I'm glad that solution currently works for you :)

When I get things fully launched, I'll make sure to include a write up on the site on how to achieve that.

If you continue to use the plugin and find things useful, I'd love it if you could leave us a positive review on the WordPress.org repository.

https://wordpress.org/support/view/plugin-reviews/timeline-express

Thanks again!
Evan
