### ISSUE TITLE
set_custom_icon_html_markup TODO

### ISSUE THREAD

**Issue by Farsk** [EvanHerman/timeline-express#22]
This code may be helpful in completing your documentation.

`add_image_size( 'timeline-img', 75, 75);

function set_custom_icon_html_markup() {
	$post_id = get_the_ID();
	$timeline_express_options = timeline_express_get_options();
	$custom_icon_html = '';
	
	if($custom_icon_url = wp_get_attachment_image_url( get_post_meta( $post_id, 'announcement_image_id', true ), 'timeline-img' )) {
		/* If read more visibility is set to true, wrap the icon in a link. */
		if ( '1' === $timeline_express_options['read-more-visibility'] ) {
			$custom_icon_html .= '<a class="cd-timeline-icon-link" href="' . esc_attr( apply_filters( 'timeline-express-read-more-link', esc_url( get_the_permalink( $post_id ) ) ) ) . '">';
		}
		
		$custom_icon_html .= '<div class="cd-timeline-img cd-picture" style="background: url(' . $custom_icon_url . ') center center no-repeat; background-size: contain;"></div>';
	
		/* If read more visibility is set to true, wrap the icon in a link. */
		if ( '1' === $timeline_express_options['read-more-visibility'] ) {
			$custom_icon_html .= '</a>';
		}
		
		echo $custom_icon_html;
	}
	
	return $custom_icon_html;
}

add_filter( 'timeline_express_custom_icon_html', 'set_custom_icon_html_markup' );`

To get this to work properly I needed to edit timeline_express_get_announcement_icon_markup() in  helpers.php because there's a mixture of outputted content and returned content. There's probably a better solution if you want to change your core code.

`if ( $custom_icon_html ) {
	return '';
}`

Sorry for poor formatting, in a rush to submit.

**Comment by EvanHerman** [comment]
Hey Farsk,

Thanks for the sample code. I'll take a look at it and add it to our documentation for future reference. I appreciate you taking the time to post that here. If need be I'll go ahead and update any code in the code base as well.

Thanks again!
Evan
