### ISSUE TITLE
Features to add

### ISSUE THREAD

**Issue by EvanHerman** [EvanHerman/timeline-express#3]
---
#### Completed:
- ~~Setting to select icon color (on announcement creation + default icon color in settings )~~ [v1.1.5]
- ~~Transients to cache front-end queries. Should clear whenever an announcement is saved (save_post hook).~~ [v1.2]
- ~~Remove AJAX save settings. Causing issue for some people who are leaving negative reviews without requesting support.~~ [v1.2]
- ~~Setting to toggle animation effects~~ [v1.2]
- ~~Limit number of posts displayed, with a 'load more' button to lazy load some more~~
- ~~Setting to define a slug for the announcement posts~~ [feature added in [v1.1.5](https://github.com/EvanHerman/Timeline-Express/releases/tag/v1.1.5)]
- ~~Premium version with multiple timelines etc.~~
- ~~Fix theme overriding Timeline Express excerpt length by adding priority and conditional.~~ [v1.2.2]
- ~~Remove 'Read More' links from the excerpts, leave as ellipses (...).~~ [v1.2.2]
- ~~Add 'Read More' link to `timeline-express-after-excerpt` hook, so the read more link is always present, regardless of excerpt length.~~ [v1.2.2]
- ~~Updates to the random excerpt length.~~ [v1.2.2]
- ~~Fix admin table responsive styles, causing weird stacking~~ [v1.2.2]
- ~~Look into date picker localization/calendar translations etc.~~ [v1.2.2] - **Option now controlled via General > Date Format**
- ~~Responsive images (not 100% width) on single announcements.~~ (srcset attr) [v1.2.7]<b>Note: </b>No more 100% width images on the single announcement template, if you need them to be 100% you can use the following CSS: 

``` css
body.single-te_announcements .announcement-banner-image { width: 100% }
```

<em>This will only target images on single announcement page templates, not on the timeline</em>
<em>Should still look into srcset attr</em>
- ~~Re-check the excerpt length not working properly.~~ (themes are most likely overriding the option, with the excerpt_length filter. Probably at a higher priority.)
- ~~Take another look at the responsiveness of the timeline on mobile devices (seems to be overflowing outside the browser window)~~.[v1.2.7] <em>timeline now adjusts to 95% width at 822px and below</em>
- ~~Set announcement containers to 100% when < 822px.~~ [v1.2.7]
- ~~Set width auto on the single announcement images.~~ [v1.2.7]
- ~~Build in support for additional international dates (https://wordpress.org/support/topic/french-date-format-issue?replies=12#post-8423928)~~ [v.1.2.7] <em>built in support for j F Y date formats, as per the request in the above forum</em>
- ~~Add missing image class to the announcement image on announcement single page (https://wordpress.org/support/topic/minor-css-class-request?replies=2) .announcement-banner-image~~ [v1.2.7.1]
- ~~Look into weird ajax breaking issue (https://wordpress.org/support/topic/problem-with-wordpress-media-library-grid-view-and-all-ajax-requests?replies=1)~~ [v1.2.8]
- ~~Tweak `public` param in cpt register array so that the items appear in searches properly based on the setting.~~ [v1.2.8 free & v1.2.6 pro]
- ~~Timelines limited to a single timeline, attempting to display filters are not working properly. Only works when multiple timelines & categories are being used.~~ [v1.2.6.2 pro]

**Comment by rboyd** [comment]
What would a reasonable bounty be for #3 (override announcement width)? We're evaluating timeline express but need wider announcements. Would pay for this feature.

**Comment by EvanHerman** [comment]
Hi rboyd,

At the moment you can easily adjust the width of the announcement container using CSS selectors provided by the plugin.

You can do something like the following in your child theme style.css file:

`css
.cd-timeline-content {
  width: 40%;
}
`

That should help out while we work on getting these things incorporated into a premium version.


Thanks,
Evan

**Comment by ismben** [comment]
Hi Folks,
is there any news about those enhacements
- Allow standard posts to be used as timeline items (via filter)
- multiple timelines

**Comment by EvanHerman** [comment]
Hey @ismben ,

I am currently working on getting a new product out the door for client and product testimonials. When that gets launched (ideally this week), I will be working on building out the new features.

I don't have a release date but I have been chipping away at them. The reason things may take a bit to be released is because I'm doing a full code audit, to ensure the best possible performance of the plugin.

With that being said, I'll be re-writing large parts of the plugin and combining a few files to decrease load times etc. In the new release, I'll also be building out some other features such as additional layouts (horizontal timeline). These enhancements and features will be included in our premium product as it's going to take some time to flesh out, develop and test these new features.

In regards to multiple timelines, that can currently be achieved using the [premium verison](https://www.evan-herman.com/wordpress-plugin/timeline-express/) of Timeline Express. You can easily define multiple timelines, assign announcements to whichever you see fit and display them based on which timeline or category they are assigned to.

I'll also be building out a Timeline Express specific site, clearly outlining the features inclded in the premium version as well as new and fully fleshed out documentation to help out with any tweaks.

I will keep everyone posted by posting here when we get closer to launching the new version.


Thanks!
Evan

**Comment by dertuerke** [comment]
can we get to upload custom icons / images to the Bubble?

**Comment by EvanHerman** [comment]
@dertuerke This is something that we are actively working on. It's not easily achieved due to the icon conflicts. The icons are expected to be font-awesome icons in the circles on the timeline, so when you use your own icon a conflict occurs.

We are currently exploring some options for this and will be releasing it as an add-on when we've come up with a reasonable solution that makes sense and works for everyone.

I'm going to be closing out this issue in favor of individual issues, which makes tracking new features and bugs a lot easier.

Thanks!
Evan
