### ISSUE TITLE
Announcement Image URL

### ISSUE THREAD

**Issue by Seifers44** [EvanHerman/Timeline-Express#8]
Hello,

this may be an easy question but please bear.

I am trying to add url to the Announcement Image. to direct to another page.

But i was not successful. please help.

Thank you for this plugin.

**Comment by EvanHerman** [comment]
Hi Seifers44,

Unfortunately this is not something that can be done out of the box, and would require additional code to make work. If that's something you are interested in, please consider purchasing the pro version and I will be glad to help you carry out that task.


Thanks,
Evan
